Support for private strategies
New nodejs strategy

Support for runtime variables (eg. SERVER=nodejs-1-local)

Prepping for first production-ready release

diff --git a/libexec/common b/libexec/common
--- a/libexec/common
+++ b/libexec/common
@@ -8,34 +8,71 @@ complain_if_interrupted() {
   trap "exit 2" 1 2 3 13 15
 }
 
+# Displays arg as an error message, red and sad
+#
+error_message() {
+  echo -e "$bldred$@$txtrst"
+}
+
+# Displays arg as a hint message, yellow and optimistic
+#
+hint_message() {
+  echo -e "$txtylw$@$txtrst"
+}
+
+# Displays arg as a success message, green and cheerful
+#
+success_message() {
+  echo -e "$bldgrn$@$txtrst"
+}
+
 # Specific failure, fail the whole script
 #
 error() {
-  echo "$txtred$1$txtrst"
+  error_message $1
   exit 1
 }
 
-# Command failed, fail the whole script
+# Command failed (not sure why), fail the whole script
 #
 fail() {
-  echo -e "$bldred FAIL $txtrst\n"
-  echo -e "Try running the command in verbose mode (-V)\n"
+  error_message "\nNot entirely sure why this failed."
+  hint_message "Re-run the command in verbose (-V|--verbose) or debug (-D|--debug) mode to gather more details about the failure."
   exit 1
 }
 
 # Command was successful
 #
 success() {
-  echo "$bldgrn DONE $txtrst"
+  success_message " DONE"
 }
 
 # Loads the .deliver file
 #
 load_app_config() {
   if [ ! -f $APP_CONFIG ]; then
-    error "Could not find a .deliver file in the current directory"
+    error "Could not find a .deliver/config file in the current directory"
   else
     . $APP_CONFIG
+  fi
+}
+
+# Ensures all required configs are set, tries to be helpful by adding some
+# sane defaults
+#
+default_app_config() {
+  . "$BASE_PATH/libexec/config"
+}
+
+# If STRATEGY or SERVER are specified at the time of invoking, overwrite
+# anything that has been set from other sources
+#
+apply_super_configs() {
+  if [ $SUPER_STRATEGY ]; then
+    STRATEGY=$SUPER_STRATEGY
+  fi
+  if [ $SUPER_SERVER ]; then
+    SERVER=$SUPER_SERVER
   fi
 }
 
@@ -44,10 +81,13 @@ load_app_config() {
 __progress() {
   local message=$1
   local style=${2:$txtwht}
+  # Last process to have gone in the background (in this context),
+  # is our command
   pid=$!
 
   echo -en "$style$message"
 
+  # If the pid exists, the process is running; use . as status indicators
   while [ $(ps -eo pid | grep $pid) ]; do
     printf '.'
     sleep 0.5
@@ -55,8 +95,10 @@ __progress() {
 
   # Wait until command finishes, otherwise fail
   wait $pid || fail
+  # Grab the command's exit code
   status=$?
 
+  # Anything but 0 means that it failed
   if [ $status = 0 ]; then
     success
   else
@@ -64,14 +106,14 @@ __progress() {
   fi
 }
 
-# Start the output with an empty line (looks better with spacing)
+# Start the output with an empty line. It just looks better with spacing.
 #
 begin() {
   echo ""
 }
 
-# Wrapper to either run the command verbosely, inline,
-# or silently, in the background
+# Wrapper to either run the command verbosely (inline),
+# or silently (in the background)
 #
 __run() {
   if [ $VERBOSE ]; then
@@ -83,7 +125,7 @@ __run() {
   fi
 }
 
-# If we reach this step, the deploy was most likely a success
+# If we reach this step, delivery was successfull
 #
 finish() {
   echo "$bldgrn"
@@ -91,15 +133,50 @@ finish() {
   echo "$txtrst"
 }
 
+# Registers a new strategy in the global STRATEGIES array
+#
+register_strategy() {
+  STRATEGIES=("${STRATEGIES[@]}" "$txtbld\n$1$txtrst - $2")
+}
+
+# List all available strategies
+#
+list_strategies() {
+  echo -e "${STRATEGIES[@]}\n"
+}
+
 # Loads the correct deliver strategy
 #
-load_strategy() {
-  local strategies_path="$BASE_PATH/strategies"
-  local strategies=$(ls $strategies_path)
-  if [[ ! $strategies =~ $STRATEGY ]]; then
-    error "This strategy does not exist. To see a list of strategies, use the -s|--strategies flag."
+load_strategy_or_list_available_strategies() {
+  # There are strategies that came with deliver itself...
+  local public_strategies_path="$BASE_PATH/strategies"
+  # You can now have a per-project strategy. I wanted to avoid a new
+  # Capistrano, but this feature is super useful.If you have a private
+  # strategy that can be open sourced, by all means, submit a pull request.
+  local private_strategies_path="$DELIVERY_ROOT/.deliver/strategies"
+
+  # Find all files in both the public & private strategies folders
+  local available_strategies=$(find $public_strategies_path $private_strategies_path -regex '^[a-zA-Z0-9/.-]*$' -type f ! -iname 'readme*')
+
+  # This will leak function names in the global namespace, but I can't think of
+  # a better way to register strategies
+  for strategy in $available_strategies; do
+    . "$strategy"
+  done
+
+  # This will display strategies and then exit if deliver was run with
+  # -s|--strategies flag
+  strategies
+
+  if [[ ! $available_strategies =~ $STRATEGY ]]; then
+    error_message "\n'$STRATEGY' strategy does not exist. The available strategies are:"
+    list_strategies
+    exit 1
   else
-    . "$strategies_path/$STRATEGY"
+    for strategy in $available_strategies; do
+      [[ ! $strategy =~ $STRATEGY ]] && continue
+      . "$strategy" && break
+    done
   fi
 }
 
