Explaining what is printed if an error occurred.
See #80

diff --git a/libexec/core b/libexec/core
--- a/libexec/core
+++ b/libexec/core
@@ -235,11 +235,21 @@ __monitor_background_jobs() {
     local _exit_status="$?"
     if [[ "$_exit_status" != 0 ]]
     then
-      error "\nFAILED $stopping $_exit_status:\n${background_jobs[$i]}\n"
+      local _host="${background_jobs_hosts[$i]}"
+      error "\nA remote command failed on:
+
+  $_host
+
+Output of the command is shown above if the --verbose option
+was used and the commands executed on that remote host are
+printed below for debugging purposes:
+
+FAILED with exit status $_exit_status:\n\n${background_jobs[$i]}\n"
     fi
   done
 
   unset background_jobs_pids
+  unset background_jobs_hosts
   unset background_jobs
 }
 
@@ -276,6 +286,7 @@ __remote() {
   local _remote_job="$1"
   local _hosts="${2:-"$HOSTS_APP_USER"}"
   background_jobs_pids=()
+  background_jobs_hosts=()
   background_jobs=()
 
   __log "${_hosts} : $_remote_job"
@@ -286,6 +297,7 @@ __remote() {
     background_jobs_pids+=("$!")
     local _background_job="ssh -o ConnectTimeout=$SSH_TIMEOUT $_host $_remote_job $SILENCE"
     background_jobs+=("$_background_job")
+    background_jobs_hosts+=("$_host")
   done
 
   __monitor_background_jobs
@@ -301,12 +313,26 @@ __sync_remote() {
   [[ $(wc -w <<< "$_hosts") -gt 1 ]] && error "Sync commands can be executed on one host only, but serveral hosts are configured ($_hosts)."
   local _host="$_hosts"
   if [[ "$VERBOSE" = "true" ]]; then
-    ssh -t -q -o ConnectTimeout="$SSH_TIMEOUT" "$_host" "$_remote_job" || error "\nFAILED $?:\n${_remote_job}\n"
+    ssh -t -q -o ConnectTimeout="$SSH_TIMEOUT" "$_host" "$_remote_job" || error "\nA remote command failed on:
+
+  $_host
+
+Output of the command is shown above and the command executed
+on that host is printed below for debugging purposes:
+
+FAILED with exit status $?:\n${_remote_job}\n"
   else
     local _output _status
     _output=$(ssh -o ConnectTimeout="$SSH_TIMEOUT" "$_host" "$_remote_job" 2>&1)
     _status=$?
-    [[ "$_status" -ne 0 ]] && echo "$_output" && error "\nFAILED $_status:\n${_remote_job}\n"
+    [[ "$_status" -ne 0 ]] && echo "$_output" && error "\nA remote command failed on:
+
+  $_host
+
+Output of the command is shown above and the command executed
+on that host is printed below for debugging purposes:
+
+FAILED with texit status $_status:\n${_remote_job}\n"
   fi
 }
 
