Pull release base image if not yet available
Pull explicitly for better error output and to display that
step if pull takes some time for large images.

diff --git a/libexec/core b/libexec/core
--- a/libexec/core
+++ b/libexec/core
@@ -391,6 +391,56 @@ __sync_local() {
   fi
 }
 
+# Executes a docker command and hides output unless --verbose flag is set.
+# The output is captured and displayed in case of a failure. If this
+# runs in a subshell e.g. to assign the output to a vaiable 
+# (a container id for instance), the output is printed.
+__docker() {
+  if [ "$(exec sh -c 'echo "$PPID"')" != "$$" ]; then
+     local _stderr _status
+     exec 3>&2 # save stderr
+     exec 2>&1 # redirect stderr to stdout because command swapps stdout <> stderr
+     # execute command with stdout <> stderr swapped
+     _stderr="$(docker $@ 3>&1 1>&2 2>&3)" || error "
+Error output: >>> -------------
+
+$_stderr
+
+<<< Error output --------------
+
+Command 'docker $@'
+
+failed with status code $?!
+
+Error output is displayed above.
+
+    " >&3 # redirect to old stderr
+  else # not in a subshell
+    if [ "$VERBOSE" = "true" ]; then
+      docker $@ || error "
+
+Command 'docker $@'
+
+failed with status code $?!
+
+Error output is displayed above.
+"
+    else # not verbose
+      local _stdout
+      _stdout="$(docker $@)" || error "
+$_stderr
+
+Command 'docker $@'
+
+failed with status code $?!
+
+Stdout and error output is displayed above."
+    fi
+  fi
+
+}
+
+
 # monitors the parent pid if edeliver is started by a mix task.
 # this is required because edeliver is started from an erlang node
 # using "Port.open({:spawn, edeliver_command}, options)" and will
diff --git a/libexec/erlang b/libexec/erlang
--- a/libexec/erlang
+++ b/libexec/erlang
@@ -418,6 +418,10 @@ EOF
     info "Creating image $DOCKER_RUN_IMAGE"
     info "Using base image $DOCKER_RELEASE_BASE_IMAGE"
     info "Tagging as ${RELEASE_VERSION}-latest"
+    if [[ -z "$(__docker images -q "$DOCKER_RELEASE_BASE_IMAGE")" ]]; then
+      info "Pulling release base image $DOCKER_RELEASE_BASE_IMAGE"
+      __docker pull "$DOCKER_RELEASE_BASE_IMAGE" || error "Failed to pull release base image $DOCKER_RELEASE_BASE_IMAGE"
+    fi
   else
     error_message "Cannot copy releases to store for store type ${RELEASE_STORE_TYPE}"; exit 2
   fi
