Use pseudo terminal when building on build host
and verbose mode is enabled. This enables user interaction
during build process, e.g when git initially asks to enter
a git user name or when mix asks for installing hex or rebar
etc. the first time. See #42

diff --git a/libexec/core b/libexec/core
--- a/libexec/core
+++ b/libexec/core
@@ -301,7 +301,7 @@ __sync_remote() {
   [[ $(wc -w <<< "$_hosts") -gt 1 ]] && error "Sync commands can be executed on one host only, but serveral hosts are configured ($_hosts)."
   local _host="$_hosts"
   if [[ "$VERBOSE" = "true" ]]; then
-    ssh -o ConnectTimeout="$SSH_TIMEOUT" "$_host" "$_remote_job" || error "\nFAILED $?:\n${_remote_job}\n"
+    ssh -t -q -o ConnectTimeout="$SSH_TIMEOUT" "$_host" "$_remote_job" || error "\nFAILED $?:\n${_remote_job}\n"
   else
     local _output _status
     _output=$(ssh -o ConnectTimeout="$SSH_TIMEOUT" "$_host" "$_remote_job" 2>&1)
