Allow to "push" release images from local registry during deploy
to local registry on deploy hosts if no release store is configured
or image was built locally only.

diff --git a/libexec/erlang b/libexec/erlang
--- a/libexec/erlang
+++ b/libexec/erlang
@@ -1030,19 +1030,44 @@ EOF
       error "Uploading release file failed\n  source: ${_release_store_path%%/}/${_release_file} on $_release_store_host\n  destination: $_dest_file_name on deploy hosts"
   elif [ "$RELEASE_STORE_TYPE" = "docker" ]; then
     local _image_name="${DOCKER_RUN_IMAGE}:${_release_version}"
-    __remote "
-      [ -f $PROFILE ] && . $PROFILE
-      set -e
-      mkdir -p ${_destination_directory} $SILENCE
-      cd ${_destination_directory} $SILENCE
-      if [ -z \"\$(docker images -q \"$_image_name\")\" ]; then
-        echo \"Pulling release image $_image_name\" $SILENCE
-        docker pull \"$_image_name\" $SILENCE || {
-          echo \"Failed to pull release image $_image_name\" >&2
-          exit 1
-        }
+    if [ "$DOCKER_PUSH" = "true" ]; then
+      # push from local docker registry on local host to local docker registry
+      # on deploy hosts using docker save / load
+      if [ "$VERBOSE" = "true" ]; then
+        echo "Pushing release image $_image_name from local docker registry"
       fi
-    "
+      __docker save "$_image_name" | gzip -c - | base64 | __remote "
+        [ -f $PROFILE ] && . $PROFILE
+        set -e
+        mkdir -p ${_destination_directory} $SILENCE
+        cd ${_destination_directory} $SILENCE
+        if [ -z \"\$(docker images -q \"$_image_name\")\" ]; then
+          echo \"Loading release image $_image_name into local registry\" $SILENCE
+          base64 -d | gzip -d | docker load $SILENCE
+          if [ -z \"\$(docker images -q \"$_image_name\")\" ]; then
+            echo \"Failed to push release image $_image_name\" >&2
+            exit 1
+          fi
+        fi
+      " || error "Failed to push image from local docker registry to docker registry on deploy host"
+    else
+      __remote "
+        [ -f $PROFILE ] && . $PROFILE
+        set -e
+        mkdir -p ${_destination_directory} $SILENCE
+        cd ${_destination_directory} $SILENCE
+        if [ -z \"\$(docker images -q \"$_image_name\")\" ]; then
+          echo \"Pulling release image $_image_name\" $SILENCE
+          docker pull \"$_image_name\" $SILENCE || {
+            echo \"Failed to pull release image $_image_name\" >&2
+            if [ \"$DOCKER_PUSH\" != \"true\" ]; then
+              echo -e \"\nUse --push flag to push $_image_name \nfrom your local docker registry to the deploy host(s)\" >&2
+            fi
+            exit 1
+          }
+        fi
+      "
+    fi
   else
     error_message "Cannot upload release for store type ${RELEASE_STORE_TYPE}"; exit 2
   fi
