Push built docker image with release to docker registry
if edeliver `build` is executed with the `--push` flag.

diff --git a/libexec/erlang b/libexec/erlang
--- a/libexec/erlang
+++ b/libexec/erlang
@@ -442,6 +442,16 @@ EOF
     error_message "Cannot copy releases to store for store type ${RELEASE_STORE_TYPE}"; exit 2
   fi
 
+  if [ "$DOCKER_PUSH" = "true" ]; then
+    status "Pusing release image to registry"
+    info "Pushing ${_committed_image}"
+    __docker push "${_committed_image}" || error "Failed to push release image ${_committed_image}"
+    info "Pushing ${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-${_built_revision}"
+    __docker push "${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-${_built_revision}" || error "Failed to push release image ${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-${_built_revision}"
+    info "Pushing ${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-${_built_branch}"
+    __docker push "${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-${_built_branch}" || error "Failed to push release image ${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-${_built_branch}"
+  fi
+
 }
 
 # copies the release from the release store
