Ensure the release version contains only valid chars for docker tags

diff --git a/libexec/erlang b/libexec/erlang
--- a/libexec/erlang
+++ b/libexec/erlang
@@ -446,20 +446,23 @@ EOF
     [ -d "$_local_release_dir" ] || error "Local release dir '${_local_release_dir}' not found!"
     __docker cp "$_local_release_dir" "${_release_container}:/${APP}" || error "Failed to copy release into release container"
     [ "$VERBOSE" = "true" ] && __docker diff "$_release_container" || :
-    info "Commiting as ${RELEASE_VERSION}-latest"
-    local _committed_image="${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-latest"
+
+    local _valid_docker_tag
+    _valid_docker_tag="$(echo "$RELEASE_VERSION" | sed 's/[^0-9A-Za-z_.-]*//g')"
+    info "Commiting as ${_valid_docker_tag}-latest"
+    local _committed_image="${DOCKER_RUN_IMAGE}:${_valid_docker_tag}-latest"
     __docker commit "$_release_container" "$_committed_image" \
       || error "Failed to commit release container"
 
     local _built_revision _build_branch
     _built_revision="$([ -n "$DOCKER_BUILD_DIR" ] && cd "$DOCKER_BUILD_DIR" 2>/dev/null && git rev-parse --short HEAD 2>/dev/null)" && {
-      info "Tagging also as ${RELEASE_VERSION}-${_built_revision}"
-      __docker tag "$_committed_image" "${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-${_built_revision}" \
+      info "Tagging also as ${_valid_docker_tag}-${_built_revision}"
+      __docker tag "$_committed_image" "${DOCKER_RUN_IMAGE}:${_valid_docker_tag}-${_built_revision}" \
         || error "Failed to tag image with built revision"
     } || hint_message "Failed to detect built revision"
     _built_branch="$([ -n "$DOCKER_BUILD_DIR" ] && cd "$DOCKER_BUILD_DIR" 2>/dev/null && git rev-parse --abbrev-ref HEAD 2>/dev/null)" && {
-      info "Tagging also as ${RELEASE_VERSION}-${_built_branch}"
-      __docker tag "$_committed_image" "${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-${_built_branch}" \
+      info "Tagging also as ${_valid_docker_tag}-${_built_branch}"
+      __docker tag "$_committed_image" "${DOCKER_RUN_IMAGE}:${_valid_docker_tag}-${_built_branch}" \
         || error "Failed to tag image with branch name"
     } || hint_message "Failed to detect built branch"
 
@@ -467,10 +470,10 @@ EOF
       status "Pusing release image to registry"
       info "Pushing ${_committed_image}"
       __docker push "${_committed_image}" || error "Failed to push release image ${_committed_image}"
-      info "Pushing ${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-${_built_revision}"
-      __docker push "${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-${_built_revision}" || error "Failed to push release image ${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-${_built_revision}"
-      info "Pushing ${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-${_built_branch}"
-      __docker push "${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-${_built_branch}" || error "Failed to push release image ${DOCKER_RUN_IMAGE}:${RELEASE_VERSION}-${_built_branch}"
+      info "Pushing ${DOCKER_RUN_IMAGE}:${_valid_docker_tag}-${_built_revision}"
+      __docker push "${DOCKER_RUN_IMAGE}:${_valid_docker_tag}-${_built_revision}" || error "Failed to push release image ${DOCKER_RUN_IMAGE}:${_valid_docker_tag}-${_built_revision}"
+      info "Pushing ${DOCKER_RUN_IMAGE}:${_valid_docker_tag}-${_built_branch}"
+      __docker push "${DOCKER_RUN_IMAGE}:${_valid_docker_tag}-${_built_branch}" || error "Failed to push release image ${DOCKER_RUN_IMAGE}:${_valid_docker_tag}-${_built_branch}"
     fi
   else
     error_message "Cannot copy releases to store for store type ${RELEASE_STORE_TYPE}"; exit 2
